version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_mongo
          - comment_mongo
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_EXTERNAL_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - back_net
      - front_net
  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
  back_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.2.0/24
